# Generated by Django 4.1.3 on 2022-11-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ChatManager", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message", old_name="created_at", new_name="sent_at",
        ),
        migrations.RemoveField(model_name="message", name="updated_at",),
    ]
