# Generated by Django 4.1.3 on 2022-11-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ChatManager", "0002_rename_created_at_message_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
