# Generated by Django 4.1.3 on 2022-11-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ChatManager", "0004_message_seen_at_alter_message_sent_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message", old_name="to_group", new_name="group",
        ),
    ]
