# Generated by Django 4.1.3 on 2022-11-21 11:53

import ProfileManager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProfileManager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=ProfileManager.models.imageFilePath
            ),
        ),
    ]
