# Generated by Django 4.1.3 on 2022-11-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProfileManager", "0002_alter_userprofile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
