# Generated by Django 4.1.3 on 2022-11-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProfileManager", "0003_userprofile_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
